In [0]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.recurrent import SimpleRNN
from keras.layers.embeddings import Embedding
from keras.layers import LSTM
import numpy as np

In [0]:
# define documents
docs = ['very good',
'very bad']
# define class labels
labels = [1,0]

In [16]:
from collections import Counter
counts = Counter()
for i,review in enumerate(docs):
  counts.update(review.split())
words = sorted(counts, key=counts.get, reverse=True)
vocab_size=len(words)
word_to_int = {word: i for i, word in enumerate(words, 1)}
encoded_docs = []
for doc in docs:
  encoded_docs.append([word_to_int[word] for word in doc.split()])
encoded_docs

[[1, 3], [1, 2]]

In [17]:
max_length = 2
padded_docs = pad_sequences(encoded_docs, maxlen=max_length,
padding='pre')
print(padded_docs)

[[1 3]
 [1 2]]


In [18]:
model = Sequential()
model.add(LSTM(1,activation='tanh', return_sequences=False,recurrent_initializer='Zeros',
recurrent_activation='sigmoid',
input_shape=(2,1),unroll=True))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',
metrics=['acc'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 1)                 12        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 2         
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
model.fit(padded_docs.reshape(2,2,1),np.array(labels).reshape(max_length,1),epochs=500)

Epoch 1/500
2/2 [==============================] - 1s 260ms/step - loss: 0.6903 - acc: 0.5000
Epoch 2/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6901 - acc: 0.5000
Epoch 3/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6900 - acc: 0.5000
Epoch 4/500
2/2 [==============================] - 0s 5ms/step - loss: 0.6898 - acc: 0.5000
Epoch 5/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6896 - acc: 0.5000
Epoch 6/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6895 - acc: 0.5000
Epoch 7/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6893 - acc: 0.5000
Epoch 8/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6892 - acc: 0.5000
Epoch 9/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6890 - acc: 0.5000
Epoch 10/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6889 - acc: 0.5000
Epoch 11/500
2/2 [==============================] - 0s 2ms/step - loss: 0.688


2/2 [==============================] - 0s 5ms/step - loss: 0.6846 - acc: 0.5000
Epoch 41/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6845 - acc: 0.5000
Epoch 42/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6843 - acc: 0.5000
Epoch 43/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6842 - acc: 0.5000
Epoch 44/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6840 - acc: 0.5000
Epoch 45/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6839 - acc: 0.5000
Epoch 46/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6837 - acc: 0.5000
Epoch 47/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6836 - acc: 0.5000
Epoch 48/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6834 - acc: 0.5000
Epoch 49/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6833 - acc: 0.5000
Epoch 50/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6831 - a

Epoch 79/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6786 - acc: 0.5000
Epoch 80/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6784 - acc: 0.5000
Epoch 81/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6782 - acc: 0.5000
Epoch 82/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6781 - acc: 0.5000
Epoch 83/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6779 - acc: 0.5000
Epoch 84/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6778 - acc: 0.5000
Epoch 85/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6776 - acc: 0.5000
Epoch 86/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6774 - acc: 0.5000
Epoch 87/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6773 - acc: 0.5000
Epoch 88/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6771 - acc: 0.5000
Epoch 89/500
2/2 [==============================] - 0s 4ms/step - loss

2/2 [==============================] - 0s 4ms/step - loss: 0.6730 - acc: 0.5000
Epoch 115/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6729 - acc: 0.5000
Epoch 116/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6727 - acc: 0.5000
Epoch 117/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6726 - acc: 0.5000
Epoch 118/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6724 - acc: 0.5000
Epoch 119/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6723 - acc: 0.5000
Epoch 120/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6721 - acc: 0.5000
Epoch 121/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6720 - acc: 0.5000
Epoch 122/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6718 - acc: 0.5000
Epoch 123/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6717 - acc: 0.5000
Epoch 124/500
2/2 [==============================] - 0s 3ms/step - loss: 0

Epoch 146/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6684 - acc: 0.5000
Epoch 147/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6683 - acc: 0.5000
Epoch 148/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6682 - acc: 0.5000
Epoch 149/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6680 - acc: 0.5000
Epoch 150/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6679 - acc: 0.5000
Epoch 151/500
2/2 [==============================] - 0s 5ms/step - loss: 0.6677 - acc: 0.5000
Epoch 152/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6676 - acc: 0.5000
Epoch 153/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6675 - acc: 0.5000
Epoch 154/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6673 - acc: 0.5000
Epoch 155/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6672 - acc: 0.5000
Epoch 156/500
2/2 [==============================] - 0s 2ms/


2/2 [==============================] - 0s 3ms/step - loss: 0.6638 - acc: 0.5000
Epoch 180/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6637 - acc: 0.5000
Epoch 181/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6635 - acc: 0.5000
Epoch 182/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6634 - acc: 0.5000
Epoch 183/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6632 - acc: 0.5000
Epoch 184/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6631 - acc: 0.5000
Epoch 185/500
2/2 [==============================] - 0s 5ms/step - loss: 0.6629 - acc: 0.5000
Epoch 186/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6628 - acc: 0.5000
Epoch 187/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6626 - acc: 0.5000
Epoch 188/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6625 - acc: 0.5000
Epoch 189/500
2/2 [==============================] - 0s 3ms/step - loss: 

2/2 [==============================] - 0s 3ms/step - loss: 0.6592 - acc: 0.5000
Epoch 211/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6590 - acc: 0.5000
Epoch 212/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6589 - acc: 0.5000
Epoch 213/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6587 - acc: 0.5000
Epoch 214/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6586 - acc: 0.5000
Epoch 215/500
2/2 [==============================] - 0s 6ms/step - loss: 0.6584 - acc: 0.5000
Epoch 216/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6583 - acc: 0.5000
Epoch 217/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6581 - acc: 0.5000
Epoch 218/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6580 - acc: 0.5000
Epoch 219/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6578 - acc: 0.5000
Epoch 220/500
2/2 [==============================] - 0s 2ms/step - loss: 0


2/2 [==============================] - 0s 3ms/step - loss: 0.6538 - acc: 1.0000
Epoch 245/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6536 - acc: 1.0000
Epoch 246/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6535 - acc: 1.0000
Epoch 247/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6533 - acc: 1.0000
Epoch 248/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6531 - acc: 1.0000
Epoch 249/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6530 - acc: 1.0000
Epoch 250/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6528 - acc: 1.0000
Epoch 251/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6527 - acc: 1.0000
Epoch 252/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6525 - acc: 1.0000
Epoch 253/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6523 - acc: 1.0000
Epoch 254/500
2/2 [==============================] - 0s 2ms/step - loss: 


2/2 [==============================] - 0s 3ms/step - loss: 0.6481 - acc: 1.0000
Epoch 279/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6479 - acc: 1.0000
Epoch 280/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6477 - acc: 1.0000
Epoch 281/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6476 - acc: 1.0000
Epoch 282/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6474 - acc: 1.0000
Epoch 283/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6472 - acc: 1.0000
Epoch 284/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6470 - acc: 1.0000
Epoch 285/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6469 - acc: 1.0000
Epoch 286/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6467 - acc: 1.0000
Epoch 287/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6465 - acc: 1.0000
Epoch 288/500
2/2 [==============================] - 0s 3ms/step - loss: 

Epoch 311/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6422 - acc: 1.0000
Epoch 312/500
2/2 [==============================] - 0s 6ms/step - loss: 0.6420 - acc: 1.0000
Epoch 313/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6418 - acc: 1.0000
Epoch 314/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6416 - acc: 1.0000
Epoch 315/500
2/2 [==============================] - 0s 6ms/step - loss: 0.6414 - acc: 1.0000
Epoch 316/500
2/2 [==============================] - 0s 8ms/step - loss: 0.6412 - acc: 1.0000
Epoch 317/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6411 - acc: 1.0000
Epoch 318/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6409 - acc: 1.0000
Epoch 319/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6407 - acc: 1.0000
Epoch 320/500
2/2 [==============================] - 0s 6ms/step - loss: 0.6405 - acc: 1.0000
Epoch 321/500
2/2 [==============================] - 0s 4ms/

Epoch 343/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6361 - acc: 1.0000
Epoch 344/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6359 - acc: 1.0000
Epoch 345/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6357 - acc: 1.0000
Epoch 346/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6355 - acc: 1.0000
Epoch 347/500
2/2 [==============================] - 0s 5ms/step - loss: 0.6353 - acc: 1.0000
Epoch 348/500
2/2 [==============================] - 0s 5ms/step - loss: 0.6351 - acc: 1.0000
Epoch 349/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6349 - acc: 1.0000
Epoch 350/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6347 - acc: 1.0000
Epoch 351/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6345 - acc: 1.0000
Epoch 352/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6343 - acc: 1.0000
Epoch 353/500
2/2 [==============================] - 0s 3ms/

Epoch 378/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6289 - acc: 1.0000
Epoch 379/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6286 - acc: 1.0000
Epoch 380/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6284 - acc: 1.0000
Epoch 381/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6282 - acc: 1.0000
Epoch 382/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6280 - acc: 1.0000
Epoch 383/500
2/2 [==============================] - 0s 1ms/step - loss: 0.6278 - acc: 1.0000
Epoch 384/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6276 - acc: 1.0000
Epoch 385/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6273 - acc: 1.0000
Epoch 386/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6271 - acc: 1.0000
Epoch 387/500
2/2 [==============================] - 0s 5ms/step - loss: 0.6269 - acc: 1.0000
Epoch 388/500
2/2 [==============================] - 0s 3ms/

2/2 [==============================] - 0s 3ms/step - loss: 0.6213 - acc: 1.0000
Epoch 412/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6211 - acc: 1.0000
Epoch 413/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6208 - acc: 1.0000
Epoch 414/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6206 - acc: 1.0000
Epoch 415/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6204 - acc: 1.0000
Epoch 416/500
2/2 [==============================] - 0s 4ms/step - loss: 0.6201 - acc: 1.0000
Epoch 417/500
2/2 [==============================] - 0s 6ms/step - loss: 0.6199 - acc: 1.0000
Epoch 418/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6196 - acc: 1.0000
Epoch 419/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6194 - acc: 1.0000
Epoch 420/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6191 - acc: 1.0000
Epoch 421/500
2/2 [==============================] - 0s 2ms/step - loss: 0

Epoch 446/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6123 - acc: 1.0000
Epoch 447/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6120 - acc: 1.0000
Epoch 448/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6117 - acc: 1.0000
Epoch 449/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6114 - acc: 1.0000
Epoch 450/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6112 - acc: 1.0000
Epoch 451/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6109 - acc: 1.0000
Epoch 452/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6106 - acc: 1.0000
Epoch 453/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6103 - acc: 1.0000
Epoch 454/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6100 - acc: 1.0000
Epoch 455/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6097 - acc: 1.0000
Epoch 456/500
2/2 [==============================] - 0s 3ms/


2/2 [==============================] - 0s 3ms/step - loss: 0.6028 - acc: 1.0000
Epoch 479/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6025 - acc: 1.0000
Epoch 480/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6022 - acc: 1.0000
Epoch 481/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6019 - acc: 1.0000
Epoch 482/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6016 - acc: 1.0000
Epoch 483/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6013 - acc: 1.0000
Epoch 484/500
2/2 [==============================] - 0s 3ms/step - loss: 0.6009 - acc: 1.0000
Epoch 485/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6006 - acc: 1.0000
Epoch 486/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6003 - acc: 1.0000
Epoch 487/500
2/2 [==============================] - 0s 2ms/step - loss: 0.6000 - acc: 1.0000
Epoch 488/500
2/2 [==============================] - 0s 2ms/step - loss: 

In [21]:
model.layers[0].get_weights()

[array([[ 1.1860023 , -0.35046005, -0.40737563,  0.51597786]],
       dtype=float32),
 array([[0.06184402, 0.20871657, 0.12195425, 0.09282562]], dtype=float32),
 array([-0.30494106,  0.99633026,  0.61977786,  0.609171  ], dtype=float32)]

In [22]:
model.layers[0].trainable_weights

[<tf.Variable 'lstm_2/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'lstm_2/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'lstm_2/bias:0' shape=(4,) dtype=float32_ref>]

In [23]:
model.layers[1].get_weights()

[array([[-1.3443611]], dtype=float32), array([-0.28975648], dtype=float32)]

In [24]:
model.layers[1].trainable_weights

[<tf.Variable 'dense_2/kernel:0' shape=(1, 1) dtype=float32_ref>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32_ref>]

In [20]:
model.predict(padded_docs[1].reshape(1,2,1))

array([[0.44851267]], dtype=float32)